### ISSUE TITLE
Re-write UI in React.JS using Flux methodology

### ISSUE THREAD

**Issue by UmiDevSec** [sandialabs/scot#1]
The Current UI does DOM manipulations itself, which is hard to maintain and isn't always the most efficient.  This suggestion is to re-write the using the Flux method of updating with React.JS.

**Comment by toddbruner** [comment]
Coming soon....

**Comment by toddbruner** [comment]
Well, maybe soon was too strong of a word!  Anyway, UI is now React.js based
