### ISSUE TITLE
Inclusion of Screenshots Would be Helpful

### ISSUE THREAD

**Issue by swannysec** [sandialabs/scot#15]
It would be extremely helpful to be able to attach screenshots, preferably via drag and drop or paste from clipboard to entries.  This will allow more thorough documentation of incidents.  For example, I may wish to include a screenshot of the alert or graph which initiated the event.

**Comment by toddbruner** [comment]
John:
This is possible currently using firefox.  Chrome and Safari have problems though.  We are working on a cross browser solution to this.  Thanks for the report,  I leave this open until we get it working for all browsers.

**Comment by johndswanson** [comment]
Thanks Todd!  Excellent to know it works in Firefox, I'll give it a shot.  Primarily a chrome user.  Otherwise, thanks for the excellent tool, I look forward to seeing it mature!

**Comment by toddbruner** [comment]
Is now working in our tests on 3.5.2.  Let me know if you have problems.
