### ISSUE TITLE
Ubuntu Installation Script

### ISSUE THREAD

**Issue by CSIRTUK** [sandialabs/scot#24]
All the references to the mongod service and logs should be updated to mongodb.  Also the script should start off by installing the package build-essentials.  

Regards
Andy Dove

**Comment by toddbruner** [comment]
We will include these in the next version we are preparing.  Thanks!

**Comment by toddbruner** [comment]
At some point I believe mongo changed from one to the other.  Anyway, new installer gets a working Mongodb installation.  Let me know if you have problems with it.
