### ISSUE TITLE
Tags don't show when entered via alert_tool.pl

### ISSUE THREAD

**Issue by ghub2015** [sandialabs/scot#35]
"Tags" do not show up in the SCOT UI when they are entered via alert_tool.pl

To reproduce:

1) Create a tag manually in the SCOT UI, for example under "Intel":

```
https://scot/#/intel/1
```
- enter "Manual" in Tags field, without quotes
- Verify that you can see "Manual" in Tags selector on the various SCOT screens

2) Create a tag programmatically by using alert_tool.pl

```
./alert_tool.pl
```
- enter "Code" in Tags field, without quotes
- Dumper will confirm POST data
- You will not find/see "Code" tag anywhere in the SCOT UI

**Comment by toddbruner** [comment]
alert_tool.pl removed, was only sample code.  See wiki entry on creating alerts via rest api
