### ISSUE TITLE
Following Instructions but not able to do bash install_scot3

### ISSUE THREAD

**Issue by alexhauber** [sandialabs/scot#36]
Here are the results when i try

root@ubuntu:~/scot# bash install_scot3
bash: install_scot3: No such file or directory
here is my LS

root@ubuntu:~/scot# ls
bin                  circle.yml  Dockerfile  etc         lib      license.txt  public     redhat_installer.sh  t          ubuntu_installer.sh
centos_installer.sh  deploy      docs        install.sh  LICENSE  pkgs         README.md  script               templates  wercker.yml
HELP

**Comment by toddbruner** [comment]
Hey Alex, we are planning on pushing a new version of SCOT on Tuesday or
Wednesday of next week.  It will include a new installer as well.

------------------------------
todd.bruner@gmail.com

**Comment by alexhauber** [comment]
Thank you appreciate it

**Comment by alexhauber** [comment]
Any News on the Update?

**Comment by toddbruner** [comment]
Unfortunately, the final reviewer in the classification office is MIA.  We
are working to get his attention, but no luck yet.  Sorry, but my best
guess would be early next week.

Todd

------------------------------
todd.bruner@gmail.com

**Comment by alexhauber** [comment]
LOL ok it's now late next week any lick? Time to charge the reviewer with AWOL LOL

**Comment by toddbruner** [comment]
Yes.  Just got approved.  On travel right now, but will attempt to get it
pushed over the weekend.

------------------------------
todd.bruner@gmail.com

**Comment by Pmastron63** [comment]
I tried installing SCOT yesterday and have the same issue.  When will the fix be uploaded?

**Comment by alexhauber** [comment]
Same Question here will the update be pushed soon?

**Comment by toddbruner** [comment]
doing final testing.  assuming all goes well by next Wednesday.  Sorry for
the delays, but I want to make sure it is solid.

------------------------------
todd.bruner@gmail.com

**Comment by toddbruner** [comment]
New installer, give it a try.
