### ISSUE TITLE
install.sh fails to get elasticsearch gpg key

### ISSUE THREAD

**Issue by KennyWap** [sandialabs/scot#40]
install.sh fails to get the elasticsearch gpg key from MIT key server and does not finish installing

**Comment by toddbruner** [comment]
Kenny:

I can not seem to duplicate this on my end.  Please verify that you have your https_proxy set correctly if you are behind a proxy.  Also test if you can hit https://packages.elastic.co/GPG-KEY-elasticsearch from a browser from the server or another computer on that network.  Finally, maybe the elastic.co site was having a temporary problem.  Please reopen if this continues and I will attempt to help you debug.

**Comment by KennyWap** [comment]
Thank you for the quick reply! How should the proxy variables be set if I
am not using a proxy? i am doing this in an Ubuntu 16.04 virtual machine. I
had previously set the http_proxy=* and https_proxy=*

**Comment by toddbruner** [comment]
OK, that's the problem!  The install assumes that SCOT will be behind a
proxy.  If you don't mind hacking install.sh, here's how you can do it:
1.  unset http_proxy and https_proxy (depends on  your shell on how to do
that)
2.  edit install.sh and comment out lines 24 through 30.
3.  Re-run install.sh with no flags.

Let me know if that fixes the problem for you

------------------------------
todd.bruner@gmail.com
