### ISSUE TITLE
Install script ends abruptly

### ISSUE THREAD

**Issue by Maleus** [sandialabs/scot#41]
Brand new instance of Ubuntu 16.04 LTS, continue to get the following error:

Proxy is not required for internet access

root@Scot:/scot# ./install.sh 2>&1 | tee scot.install.log
==================== SCOT 3.5 Installer =======================
DEVDIR is /scot
Running as root: Yes
~~~~~ Determining http Proxy settings
http_proxy  =
!!! http_proxy not set! if you are behind a proxy, install will
!!! likely fail.  If you are using "sudo" to install use the
!!! "-E" option to preserve your environment variables
root@Scot:/scot#

**Comment by toddbruner** [comment]
Bug fixes final got approved for release.  We will be doing a push up on Monday.  Sorry for the difficulties.

**Comment by toddbruner** [comment]
New install gives you the option to continue without proxy vars being set.
