### ISSUE TITLE
Demo site down ?

### ISSUE THREAD

**Issue by GuiGuiSoft** [sandialabs/scot#43]
Hello,

I try to access the demo website https://52.12.122.162/ but it does not response. Is the server still up ? Is there a new adress.

_(I don't know if it is the right place to ask : feel free to redirect me if necessary)._
Regards.

**Comment by angeorgieff** [comment]
The demo site url has changed. It can now be accessed at https://scotdemo.com

We've updated the README with the login information: https://github.com/sandialabs/scot#scot-online-demo

**Comment by GuiGuiSoft** [comment]
Thank you. I picked up the wrong address from this page : https://hub.docker.com/r/sandialabs/scot/ ;)

**Comment by GuiGuiSoft** [comment]
By the way 

- Are there any restriction on the demo website (I can not create group of users and the are several errors)
- Is there a better place to ask fonctional questions than here (I have a lot :) )?

**Comment by angeorgieff** [comment]
The demo website, as well as the github repo, both have new code getting prepared to be pushed up. Any errors you are seeing will likely be resolved at that time. 

You can send an email to scot-dev@sandia.gov with your questions.

**Comment by toddbruner** [comment]
Please feel free to post your questions as issues and we will do our best
to answer.
Thanks!

------------------------------
todd.bruner@gmail.com
