### ISSUE TITLE
Docker-Perl does not install

### ISSUE THREAD

**Issue by FusionFC** [sandialabs/scot#52]
Installing scot from master branch, under Ubuntu 16.04, using latest docker-ce, perl did not build properly.  Error during the 'cpanm' call was:
`Configuring IO-AIO-4.6 ... ! Configure failed for IO-AIO-4.6. See /root/.cpanm/work/1536269103.6/build.log for details.
`

This is caused by not including libperl-dev in the docker image.  Including the package in the Dockerfile-Perl will allow for IO-AIO to build properly and for the docker image to be created.

**Comment by brymon68** [comment]
@FusionFC  - I will post a fix now. In the mean time, if you add a @4.5 to that CPAN module (IO::AIO), that should fix it. I submitted a bug report a few weeks ago to the author, but have not heard anything back.

**Comment by brymon68** [comment]
We have pegged IO::AIO at v 4.5 which has resolved the issue. Thanks for catching this.

**Comment by brymon68** [comment]
We have pegged IO::AIO at v 4.5 which has resolved the issue. Thanks for catching this.

**Comment by brymon68** [comment]
We have pegged IO::AIO at v 4.5 which has resolved the issue. Thanks for catching this.

**Comment by FusionFC** [comment]
Hmm, ok, it seems as if just adding `libperl-dev` to the `apt install` allows 4.6 to build properly.  It was the configure stage that was failing.
