### ISSUE TITLE
game exited with code 255

### ISSUE THREAD

**Issue by FusionFC** [sandialabs/scot#54]
On clean install I see the following:
`game        | Can't locate object method "location" via package "Scot::Env" at /opt/scot/lib/Scot/Collection.pm line 40.
game        | --- Starting Game Tally ---
game exited with code 255`

It would appear a default "location" is not defined in the game.cfg.pl.  Defining it in `docker-configs/game/game.cfg.pl` and re-issuing appears to resolve the issue although I need to test a clean install to be sure.

scot.cfg.pl and others define "location" as being for "future use".  I simply copied one of these definitions over.  Note there is an inconsistency in the defaults as most cfg.pl define location as "scot_demo" where scot.cfg.pl defines it as "demosite".  Same applies to "site_identifier".

**Comment by brymon68** [comment]
This should now be fixed. Updated docker-configs/game/game.cfg.pl file to add 'location' key / value.
