### ISSUE TITLE
mongodb errors on first-time login

### ISSUE THREAD

**Issue by jbfeldman** [sandialabs/scot#59]
I just installed scot, but I'm having problems trying to login for the first time. Initially I faced LDAP auth issues, and I disabled LDAP per https://github.com/sandialabs/scot/issues/47. After restarting the server, I'm now getting MongoDB errors when trying to login. Trying to login via localhost/login redirects me to localhost/auth and yields the following error message 
`find_one error: MongoDB SelectionError: No readable server available for matching read preference primary. MongoDB server status:
Topology type: Singe; Member status:
127.0.0.1:27017 (type Unknown, error: MongoDB::NetworkError: Could not connect to '127.0.0.1:27017': Connection Refused) at usr/local/share/perl/5.26.1/Meerkat/Collection.pm line 217`

Do I need to manually start the MongoDB instance or is it something else? Any help would be greatly appreciated

**Comment by brymon68** [comment]
hi @jbfeldman  - Which method of installation did you choose? Docker? Or did you just run install.sh script?

**Comment by jbfeldman** [comment]
Ah, probably should've mentioned that. I ran the install.sh script on ubuntu

**Comment by brymon68** [comment]
@jbfeldman  - No problem! Docker is now the preferred method for installation. You can read about that here: https://github.com/sandialabs/scot/blob/master/docs/source/scotdocker.rst

Let me know if you run into any issues and I can help!

**Comment by toddbruner** [comment]
the install.sh should have started mongodb for you though.  What OS version are you using.  Systemd may have changed since we last tested.  

The error definitely is saying that Mongo isn't running, so you can 
`systemctl restart mongod scot apache2`
and see if it works.

**Comment by jbfeldman** [comment]
that did the trick! Thanks!
