### ISSUE TITLE
Failed to log in due to bad CSRF token. Please reload the page and then log in. Error: Failed CSRF check

### ISSUE THREAD

**Issue by san3ncrypt3d** [sandialabs/scot#60]
I had this issue after installing scot on my local machine and i noticed the same error on the demo page of scot

<img width="1326" alt="Screen Shot 2020-06-24 at 11 51 58 AM" src="https://user-images.githubusercontent.com/32395477/85589159-55e52000-b611-11ea-85de-e5faf95c581d.png">

**Comment by toddbruner** [comment]
Try the following:  do a hard reload of the browser page.  If that doesn't clear it, you may have to clear cache for the site and restart browser.
