### ISSUE TITLE
build failed on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [sandialabs/scot#61]
[root@cn05 scot]# ./install.sh 2>&1 | tee ../scot.install.log
...
=========== installing APACHE =============
---
--- Installing Apache2
---
--
-- CENT/RH based system install of apache2
--
Last metadata expiration check: 2:51:35 ago on Thu 25 Mar 2021 11:28:19 AM CET.
Package httpd-2.4.46-9.fc33.aarch64 is already installed.
Package mod_ssl-1:2.4.46-9.fc33.aarch64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
-- adding firewalld command to allow web traffic
FirewallD is not running
FirewallD is not running
FirewallD is not running
--
-- configuring apache2
--
-- DEVDIR is /data/jw/scot
-- CSD    is /data/jw/scot/install/src/apache2
- looking for /data/jw/scot/../Scot-Internal-Modules/etc/scot-revproxy.conf
- looking for /data/jw/scot/install/src/apache2/scot-revproxy-Fedora.conf
 FAILED to FIND revproxy config!
Installation can not proceed until fixed!
[root@cn05 scot]# 

'firewalld' is yum installed.

**Comment by toddbruner** [comment]
I've never tried to install SCOT on that particular OS/version, so we may be in for a rough ride!
Essentially the error that is blocking you is the lack of a default config for that arch.  If you look in /data/jw/scot/install/src/apache2, you will see default apache configs for Cent, RHEL and Ubuntu.   

Copy `scot-revproxy-CentOS.conf `to `scot-revproxy-Fedora.conf`.   (You might want to browse through the config and make sure it will work in your local environment)

After creating scot-revproxy-Fedora.conf, restart the install process, with:
```
cd /data/jw/scot
sudo -E ./install.sh
```          (or  `install.sh -s `if all prerequisites have already been installed)

**Comment by toddbruner** [comment]
Also, if the Fedora path throughs up too many obstacles, you can try the Docker version.

**Comment by LutzWeischerFujitsu** [comment]
I tried again, according to your description. After lots of activities I get finally: 

FAILED to FIND revproxy config!
Installation can not proceed until fixed!

**Comment by toddbruner** [comment]
You will need to create
a  /data/jw/scot/install/src/apache2/scot-revproxy-Fedora.conf file based
on the Cent or RH version in the same directory.
I've never tested on Fedora, but Cent should be close.
The installer is looking for $DEVDIR/scot-rev-proxy-$ARCH.conf file.  The
three files I provide are for "CentOS", "Ubuntu" and "rh-7".

So if you do this:
cd /data/jw/scot/install/src/apache2
cp scot-revproxy-CentOS.conf scot-revproxy-Fedora.conf
cd /data/js/scot
./install.sh | tee /data/jw/install.log

you should get past that error.
if you get another error send me /data/jw/install.log

Todd


------------------------------
***@***.***

**Comment by LutzWeischerFujitsu** [comment]
That helped, but I run into other issues, so I'm stopping here for now, considering to continue later on.

**Comment by toddbruner** [comment]
understood, but can't help fix problems that are not shared.
------------------------------
***@***.***
