### ISSUE TITLE
Integrate MISP Platform

### ISSUE THREAD

**Issue by azet** [sandialabs/scot#67]
Hi,

Not for nothing, this is a nice tool and well intentioned, I have the feeling what you're really looking for to use is MISP. it has many extensions and you could very well integrate it into the workflow you have got already setup in your production scot instance (assuming there is one, the demo doesn't really show any data). The issue being: MISP is globally developed and has a very good stream of open and closed threat intelligence and other intellgience sources from IoT to private companies, finance to law enforcement, gov. depending who you share with. Many MISP streams are fully open. By now it's very extensive and even commercial tools like rapid7's threat intel tool can't really compete except for a few items where you pay for information that's only accessible if you've got the right darknet/botnet credentials (which you pay for with any online threat intel / SoC vendor anyway).

Please give it a try or at least look through the docs and a demo instance: https://www.misp-project.org/ 
NATO used to develop and use it for a long time, all the major european CIRT/CERTs use it as a sharing platform as well.

All the best from across the ocean,
azet / former HPC site admin + dev, ex-pentester+crypto/net-stack attacker/IETF sec. contributor.

**Comment by toddbruner** [comment]
Thank you for your comment, although it is odd to open an issue to promote a different system.

MISP primary focus is threat intel and in this it has overlap with SCOT.  Where SCOT shines, is marrying the incident response tracking with threat intel development through "Flair".  SCOT can immediately highlight if any IOC's in your fresh intel report have ever appeared in your previous alert or incident responses or vice versa, providing instant context to a distributed team of analysts.

Also it is not a binary choice to use MISP or SCOT.  SCOT aims to work with any data source to make the job of the incident responder or threat intel analyst easier.  

BTW, watch this space, we are awaiting approval to release the next major version of SCOT that will bring new capabilities such as SOAR and a refreshed technology stack.

**Comment by thomasboegl1** [comment]
Hi @toddbruner, bumping this topic, do you have any idea when this new major version will be released ?

**Comment by toddbruner** [comment]
We are polishing the documentation prior to release.  We expect to release
end of the month, but probably will be in a new repo.  We will update the
SCOT 3 README to point to the new repo.
------------------------------
***@***.***
