### ISSUE TITLE
Restoring data from a backup via docker (and possible the regular installer as well)

### ISSUE THREAD

**Issue by sandywater** [sandialabs/scot#7]
via @ahoying 

> The restore.sh process did take a little work, I had to copy the backup file to /opt/sandia/webapps/scot3/restore/restore.tgz for it to start, and then manually restore the scotfiles since the path in the tar didn't match up with the script, but I was able to successfully restore my database to the new docker container.

**Comment by toddbruner** [comment]
as of 3.5.2, there is no longer a restore.sh.  See documentation for manual restore procedure.
